"""
py2app build config for Sentrial.app — the Mac menubar front-end.

What this ships:
  - A minimal PyObjC menubar that loads the Railway-served PWA in a
    WKWebView (see sentrial/inputs/menubar.py).
  - The native Swift mic helper (Sentrial.app/Contents/MacOS/sentrial-mic)
    so Voice Mode's mic capture is attributed to this app bundle.

Why py2app and not a shim .app:
  When a binary asks for mic access, macOS TCC attributes the request to
  whichever bundle physically contains that binary. Our earlier attempt
  (Sentrial.app with a shell shim that execs /Library/…/Python.app/…/Python)
  failed because after exec the running binary was still Python.app, whose
  signed Info.plist has no NSMicrophoneUsageDescription — silent deny.
  py2app produces a bundle where the Python interpreter literally lives at
  Sentrial.app/Contents/Frameworks/Python.framework/…/Python, so the
  bundle's own Info.plist applies. With NSMicrophoneUsageDescription set,
  TCC prompts on first use, and ad-hoc codesigning (auto-added by py2app
  on ARM64) is sufficient — no Apple Developer ID needed for personal use.

Build:
    ./scripts/build_py2app.sh      (convenience wrapper)
  or:
    ./.venv/bin/python setup_py2app.py py2app --arch=arm64
"""
from __future__ import annotations

import os
from pathlib import Path
from setuptools import setup

# py2app 0.28 refuses when Distribution.install_requires is non-empty, on
# the assumption that bundled apps should declare deps via `packages` /
# `includes` in py2app options. Setuptools auto-populates install_requires
# from pyproject.toml's [project].dependencies, so every py2app run in this
# repo would hit that guard. Wrap py2app's build_app.finalize_options to
# clear install_requires on the Distribution before its check runs.
import py2app.build_app as _pb
_orig_build_finalize = _pb.py2app.finalize_options
def _fin(self):  # noqa: ANN001
    # Clear install_requires so the py2app guard (line ~657 of build_app.py)
    # doesn't reject. This is safe because py2app uses `packages`/`includes`
    # lists (below) to decide what to bundle — install_requires is only
    # checked to catch users who think setuptools' deps list drives bundling.
    self.distribution.install_requires = None
    _orig_build_finalize(self)
_pb.py2app.finalize_options = _fin

HERE = Path(__file__).parent

# Tiny launcher that just calls menubar.run(). py2app prefers a top-level
# script that isn't part of a package tree, so we synthesize one in-memory.
LAUNCHER = HERE / "build" / "_py2app_launcher.py"
LAUNCHER.parent.mkdir(exist_ok=True)
LAUNCHER.write_text(
    "# Generated by setup_py2app.py — DO NOT EDIT.\n"
    "from sentrial.inputs.menubar import run\n"
    "if __name__ == '__main__':\n"
    "    run()\n"
)

PLIST = {
    "CFBundleName":        "Sentrial",
    "CFBundleDisplayName": "Sentrial",
    "CFBundleIdentifier":  "com.sentrial.menubar",
    "CFBundleShortVersionString": "1.0",
    "CFBundleVersion":     "1",
    "LSMinimumSystemVersion": "11.0",
    "NSHighResolutionCapable": True,
    # Menubar-only: no Dock icon, no main window.
    "LSUIElement": True,
    # TCC usage strings — REQUIRED. Without these, macOS silently denies
    # the mic / Input Monitoring requests rather than prompting.
    "NSMicrophoneUsageDescription":
        "Sentrial uses the microphone for Voice Mode so you can speak "
        "with the assistant.",
    "NSInputMonitoringUsageDescription":
        "Sentrial monitors the Right-Option key as a global hotkey to "
        "toggle Voice Mode.",
    # We talk to api.deepgram.com / the Railway backend over TLS; no need
    # for App Transport Security exceptions.
    "NSAppTransportSecurity": {"NSAllowsArbitraryLoads": False},
}

OPTIONS = {
    "argv_emulation": False,
    "plist": PLIST,
    # Packages bundled in full (every submodule). Keeping this tight — the
    # menubar itself has a narrow dep surface; networking + JSON handling
    # is standard lib. Deepgram STT runs via the Swift helper, not Python.
    "packages": [
        "sentrial",
        "objc",
        "Foundation",
        "AppKit",
        "WebKit",
    ],
    # Single modules that don't need full-package bundling.
    "includes": [
        "certifi",
        "websockets",
        "httpx",
        "anthropic",
        "pydantic",
        "yaml",
    ],
    "excludes": [
        # Big things we don't need in the menubar (server-side).
        "uvicorn", "fastapi", "fastapi.staticfiles", "starlette",
        "cryptography", "pywebpush", "sqlite3", "typer",
        # Test + build tooling.
        "tests", "pytest", "py2app", "setuptools",
        # Skip — Voice Mode uses the native Swift helper, not sounddevice.
        "sounddevice", "numpy", "cffi",
        # Deepgram SDK — we talk to /v1/listen directly with websockets.
        "deepgram",
    ],
    # Embed Python as a standalone framework so the bundle is self-
    # contained. Ad-hoc codesign happens automatically on ARM64.
    "semi_standalone": False,
    "strip": True,
    # Bundle our evolution/base templates so reset works out of the box.
    "resources": [
        "sentrial/evolution/base",
        "sentrial/ui",
        "sentrial/config",
        # Pre-built Swift helper lives here and we copy it into MacOS/
        # after py2app finishes — see scripts/build_py2app.sh.
    ],
    "iconfile": None,
}

if os.environ.get("PY2APP_ICON") and Path(os.environ["PY2APP_ICON"]).is_file():
    OPTIONS["iconfile"] = os.environ["PY2APP_ICON"]

setup(
    name="Sentrial",
    app=[str(LAUNCHER)],
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
