#!/usr/bin/env bash
# Build Sentrial.app — a minimal macOS app bundle that wraps the menubar
# Python entrypoint so TCC attributes mic + Input Monitoring to Sentrial
# instead of to Python.app (whose Info.plist lacks usage descriptions and
# therefore causes silent denial of mic access).
#
# Idempotent. Safe to re-run. The app contains a shim shell script that
# execs the project's venv python.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"
app="$here/Sentrial.app"
bundle_id="com.sentrial.menubar"

echo "-> Building $app"
rm -rf "$app"
mkdir -p "$app/Contents/MacOS"
mkdir -p "$app/Contents/Resources"

# Copy the logo if present so the .app has a proper icon in Finder.
if [[ -f "$here/sentrial/ui/logo-192.png" ]]; then
    cp "$here/sentrial/ui/logo-192.png" "$app/Contents/Resources/AppIcon.png"
fi

cat > "$app/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>           <string>Sentrial</string>
    <key>CFBundleDisplayName</key>    <string>Sentrial</string>
    <key>CFBundleIdentifier</key>     <string>$bundle_id</string>
    <key>CFBundleExecutable</key>     <string>Sentrial</string>
    <key>CFBundlePackageType</key>    <string>APPL</string>
    <key>CFBundleShortVersionString</key> <string>1.0</string>
    <key>CFBundleVersion</key>        <string>1</string>
    <key>LSMinimumSystemVersion</key> <string>11.0</string>
    <key>NSHighResolutionCapable</key> <true/>
    <!-- Menubar-only: no Dock icon, no main window. -->
    <key>LSUIElement</key> <true/>
    <!-- TCC usage strings: required for prompts to appear. -->
    <key>NSMicrophoneUsageDescription</key>
    <string>Sentrial uses the microphone for Voice Mode so you can speak with the assistant.</string>
    <key>NSInputMonitoringUsageDescription</key>
    <string>Sentrial monitors the Right-Option key as a global hotkey to toggle Voice Mode.</string>
</dict>
</plist>
PLIST

# Compile the native mic capture helper with an embedded Info.plist (in the
# Mach-O __TEXT,__info_plist section). Without this, the binary has no mic
# usage description for macOS to display when it would prompt, so TCC
# auto-denies without showing a dialog.
if [[ -f "$here/native/sentrial-mic.swift" ]]; then
    echo "-> Compiling native/sentrial-mic.swift (with embedded Info.plist)"
    helper_plist="$(mktemp -t sentrial-mic-info.XXXXXX.plist)"
    cat > "$helper_plist" <<HPLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key> <string>com.sentrial.mic</string>
    <key>CFBundleName</key>       <string>Sentrial</string>
    <key>CFBundleExecutable</key> <string>sentrial-mic</string>
    <key>NSMicrophoneUsageDescription</key>
    <string>Sentrial uses the microphone for Voice Mode so you can speak with the assistant.</string>
</dict>
</plist>
HPLIST
    swiftc -O -target arm64-apple-macos11 \
        "$here/native/sentrial-mic.swift" \
        -o "$app/Contents/MacOS/sentrial-mic" \
        -framework AVFoundation -framework Foundation \
        -Xlinker -sectcreate \
        -Xlinker __TEXT \
        -Xlinker __info_plist \
        -Xlinker "$helper_plist"
    rm -f "$helper_plist"
else
    echo "-> WARNING: native/sentrial-mic.swift missing — Voice Mode mic will fail"
fi

# Shim: launchd launches THIS; it execs the venv python's menubar module.
# Using exec replaces the shell so the launchd-managed pid is Python itself,
# which keeps KeepAlive + the process-tree semantics clean. Python locates the
# mic helper relative to its own argv0 via Sentrial.app/Contents/MacOS/.
cat > "$app/Contents/MacOS/Sentrial" <<SHIM
#!/bin/bash
# Sentrial.app shim — generated by scripts/build_app.sh. Do not edit.
cd "$here"
export SENTRIAL_MIC_HELPER="$app/Contents/MacOS/sentrial-mic"
exec "$here/.venv/bin/python" -m sentrial.inputs.menubar
SHIM
chmod +x "$app/Contents/MacOS/Sentrial"

# Strip extended attributes LAST — swiftc + cp both add them, and codesign
# refuses any file with "resource fork, Finder information, or similar
# detritus". This must run after every file in the bundle is in place.
xattr -cr "$app"

# Ad-hoc sign. For a user-local tool this is enough — we're not distributing.
# Without signing, macOS may refuse to let the .app's Info.plist take effect
# as the TCC responsible bundle.
codesign --force --sign - --deep "$app" 2>&1 | sed 's/^/   /'

echo "-> Built $app"
echo "   Verify signature:  codesign -dv '$app'"
